set( CMAKE_SYSTEM_NAME Linux )
set( CMAKE_SYSTEM_PROCESSOR arm )
set( CMAKE_C_COMPILER arm-angstrom-linux-gnueabi-gcc )
set( CMAKE_CXX_COMPILER arm-angstrom-linux-gnueabi-g++ )
set( CMAKE_C_FLAGS "-march=armv5te -mtune=arm926ej-s -mthumb-interwork -mno-thumb  --sysroot=$ENV{SDK_PATH}/$ENV{TARGET_SYS} " CACHE STRING "OpenEmbedded CFLAGS" )
set( CMAKE_CXX_FLAGS "-march=armv5te -mtune=arm926ej-s -mthumb-interwork -mno-thumb  --sysroot=$ENV{SDK_PATH}/$ENV{TARGET_SYS}  -fpermissive" CACHE STRING "OpenEmbedded CXXFLAGS" )
set( CMAKE_C_FLAGS_RELEASE "-fexpensive-optimizations -fomit-frame-pointer -frename-registers -O2 -ggdb2 -DNDEBUG" CACHE STRING "CFLAGS for release" )
set( CMAKE_CXX_FLAGS_RELEASE "-fexpensive-optimizations -fomit-frame-pointer -frename-registers -O2 -ggdb2 -DNDEBUG" CACHE STRING "CXXFLAGS for release" )
set( CMAKE_FIND_ROOT_PATH $ENV{SDK_PATH} $ENV{SDK_PATH}/$ENV{TARGET_SYS})
set( CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY )
set( CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY )
set( CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY )
set( CMAKE_INSTALL_RPATH  )
